# Generated by Django 5.1.7 on 2025-07-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image_url',
            field=models.URLField(default='https://i.imgur.com/7suwDp5.jpeg'),
        ),
    ]
