# Generated by Django 5.1.7 on 2025-07-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='google_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='type',
            field=models.CharField(choices=[('manual', 'Manual'), ('google', 'Google'), ('link', 'Link')], default='manual', max_length=20),
        ),
    ]
