# Generated by Django 5.1.7 on 2025-07-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_appuser_login_emailaction_scheduledtask_todotask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
