# Generated by Django 5.2.4 on 2025-08-10 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_appuser_fcm_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledtask',
            old_name='is_done',
            new_name='done',
        ),
        migrations.RenameField(
            model_name='scheduledtask',
            old_name='calendar_event_id',
            new_name='email_subject',
        ),
        migrations.RemoveField(
            model_name='scheduledtask',
            name='email_id',
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='email_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='schedule_type',
            field=models.CharField(choices=[('email', 'Email Schedule'), ('calendar', 'Google Calendar Task')], default='calendar', max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.appuser'),
        ),
    ]
