# Generated by Django 5.2.4 on 2025-08-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_is_done_scheduledtask_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='google_event_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
