# Generated by Django 5.2.4 on 2025-08-17 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_scheduledtask_google_event_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_uid', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
