# Generated by Django 5.2.4 on 2025-09-09 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_appuser_expire'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignored_email', models.EmailField(max_length=254)),
                ('count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignored_emails', to='core.appuser')),
            ],
            options={
                'unique_together': {('user', 'ignored_email')},
            },
        ),
    ]
