# Generated by Django 5.2.4 on 2025-09-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ignoredemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=200, unique=True)),
                ('classification', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
