# Generated by Django 5.2.4 on 2025-09-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_emailclassification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailclassification',
            name='summary',
        ),
        migrations.AlterField(
            model_name='emailclassification',
            name='classification',
            field=models.TextField(),
        ),
    ]
