# Generated by Django 5.2.4 on 2025-09-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_emailsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='last_notified_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
