# Generated by Django 5.2.4 on 2025-12-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_appuser_last_notified_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenRouterAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('requests_today', models.PositiveIntegerField(default=0)),
                ('last_reset', models.DateField(auto_now=True)),
            ],
        ),
    ]
